### ISSUE TITLE
The JSON value could not be converted to System.Int32. Path:

### ISSUE THREAD

**Issue by primushkodenis** [glad-tidings/BumsBot#6]
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.lists[21].nextLevelCost | LineNumber: 0 | BytePositionInLine: 5177.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.ThrowHelper.ThrowFormatException(NumericType numericType)
   at System.Text.Json.Serialization.Converters.Int32Converter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)

**Comment by glad-tidings** [comment]
fix this error
